service: test-service

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  localPath: '../../'
  modules:
    - serverless-local-schedule

functions:
  hello:
    handler: handler.hello
    events:
      - schedule:
          rate: cron(0 10 * * ? *)
          name: test-crontab
          timezone: America/New_York
      - schedule:
          rate: cron(0 5 * * ? *)
          timezone: America/New_York
